### ISSUE TITLE
Scopes don't work as intended

### ISSUE THREAD

**Issue by chrissvo** [phobosjs/phobos.js#29]
Using a scope like this on a user that has both `client` and `user` scope.

``` js
show: {
  scope: [ '*', 'owner', 'client', 'admin' ],
  leanQuery: false
}
```

I'm expecting my API to return `client` scoped parameters, instead I get `*` scoped parameters.
# hopelesslybroken

**Comment by mtimofiiv** [comment]
This is now fixed in release `1.2.3`.
