### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mtimofiiv** [phobosjs/phobos.js#5]
Write some docs!!! How? What? Where? When? Why?

**Comment by adriaandotcom** [comment]
Is live http://phobos.fiiv.io :+1:

**Comment by mtimofiiv** [comment]
Yes, but I do need to document better a couple of the features.

**Comment by mtimofiiv** [comment]
Going to close this, as version `1.x` is going to launch soon and https://github.com/fiiv/phobos.js/issues/15 covers docs for that.
