### ISSUE TITLE
Add migrations

### ISSUE THREAD

**Issue by adriaandotcom** [phobosjs/phobos.js#6]
That would be nice!

**Comment by mtimofiiv** [comment]
This is not a bad idea. However, this can take the form of an existing Mongoose plugin such as [madhums/mongoose-migrate](https://github.com/madhums/mongoose-migrate).

The best way to do this would be to create an easy interface for adding Mongoose plugins via a method or expose the Mongoose object for this.

This way, this will give all the flexibility of Mongoose plugins to the framework.
